version: '3'

networks:
  openim-server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${DOCKER_BRIDGE_SUBNET:-172.28.0.0/16}'
          gateway: '${DOCKER_BRIDGE_GATEWAY:-172.28.0.1}'

services:
  mysql:
    image: mysql:${MYSQL_IMAGE_VERSION:-5.7}
    ports:
      - "${MYSQL_PORT:-13306}:3306"
    container_name: mysql
    volumes:
      - "${DATA_DIR:-./}/components/mysql/data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-openIM123}"
    restart: always
    networks:
      openim-server:
        ipv4_address: ${MYSQL_NETWORK_ADDRESS:-172.28.0.15}

  mongodb:
    image: mongo:${MONGODB_IMAGE_VERSION-6.0.2}
    ports:
      - "${MONGO_PORT:-37017}:27017"
    container_name: mongo
    command: --wiredTigerCacheSizeGB 1 --auth
    volumes:
      - "${DATA_DIR:-./}/components/mongodb/data/db:/data/db"
      - "${DATA_DIR:-./}/components/mongodb/data/logs:/data/logs"
      - "${DATA_DIR:-./}/components/mongodb/data/conf:/etc/mongo"
      - "./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
    environment:
      - TZ=Asia/Shanghai
      - wiredTigerCacheSizeGB=1
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-openIM123}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-openIM_v3}
    restart: always
    networks:
      openim-server:
        ipv4_address: ${MONGO_NETWORK_ADDRESS:-172.28.0.2}

  redis:
    image: redis:${REDIS_IMAGE_VERSION:-7.0.0}
    container_name: redis
    ports:
      - "${REDIS_PORT:-16379}:6379"
    volumes:
      - "${DATA_DIR:-./}/components/redis/data:/data"
      - "${DATA_DIR:-./}/components/redis/config/redis.conf:/usr/local/redis/config/redis.conf"
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass ${REDIS_PASSWORD:-openIM123} --appendonly yes
    networks:
      openim-server:
        ipv4_address: ${REDIS_NETWORK_ADDRESS:-172.28.0.3}

  zookeeper:
    image: bitnami/zookeeper:${ZOOKEEPER_IMAGE_VERSION:-3.8}
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT:-12181}:2181"
    volumes:
      - "/etc/localtime:/etc/localtime"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ="Asia/Shanghai"
    restart: always
    networks:
      openim-server:
        ipv4_address: ${ZOOKEEPER_NETWORK_ADDRESS:-172.28.0.5}

  kafka:
    image: 'bitnami/kafka:${KAFKA_IMAGE_VERSION:-3.5.1}'
    container_name: kafka
    user: root
    restart: always
    ports:
      - "${KAFKA_PORT:-19094}:9092"
    volumes:
      - ./scripts/create-topic.sh:/opt/bitnami/kafka/create-topic.sh
      - ${DATA_DIR:-./}/components/kafka:/bitnami/kafka
    command: >
      bash -c "
      /opt/bitnami/scripts/kafka/run.sh & sleep 5; /opt/bitnami/kafka/create-topic.sh; wait
      "
    environment:
       - TZ=Asia/Shanghai
       - KAFKA_CFG_NODE_ID=0
       - KAFKA_CFG_PROCESS_ROLES=controller,broker
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@<your_host>:9093
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://${DOCKER_BRIDGE_GATEWAY:-172.28.0.1}:${KAFKA_PORT:-9092}
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      openim-server:
        ipv4_address: ${KAFKA_NETWORK_ADDRESS:-172.28.0.4}

  minio:
    image: minio/minio:${MINIO_IMAGE_VERSION:-latest}
    ports:
      - "${MINIO_PORT:-10005}:9000"
      - "9090:9090"
    container_name: minio
    volumes:
      - "${DATA_DIR:-./}/components/mnt/data:/data"
      - "${DATA_DIR:-./}/components/mnt/config:/root/.minio"
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY:-root}"
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY:-openIM123}"
    restart: always
    command: minio server /data --console-address ':9090'
    networks:
      openim-server:
        ipv4_address: ${MINIO_NETWORK_ADDRESS:-172.28.0.6}

  openim-web:
    image: ${IMAGE_REGISTRY:-ghcr.io/openimsdk}/openim-web:${OPENIM_WEB_IMAGE_VERSION:-latest}
    container_name: openim-web
    environment:
      - OPENIM_WEB_DIST_PATH=${OPENIM_WEB_DIST_PATH:-/app/dist}
      - OPENIM_WEB_PORT=${OPENIM_WEB_PORT:-11001}
    restart: always
    ports:
      - "${OPENIM_WEB_PORT:-11001}:11001"
    networks:
      openim-server:
        ipv4_address: ${OPENIM_WEB_NETWORK_ADDRESS:-172.28.0.7}

  openim-server:
    image: ${IMAGE_REGISTRY:-ghcr.io/openimsdk}/openim-server:${SERVER_BRANCH:-main}
    container_name: openim-server
    ports:
      - "${OPENIM_WS_PORT:-10001}:10001"
      - "${API_OPENIM_PORT:-10002}:10002"
    healthcheck:
      test: ["CMD", "/openim/openim-server/scripts/check-all.sh"]
      interval: 60s
      timeout: 10s
      retries: 5
    volumes:
      - "./openim-server/logs:/openim/openim-server/logs"
      - "./openim-server/_output/logs:/openim/openim-server/_output/logs"
      - "./openim-server/config:/openim/openim-server/config"
    restart: always
    entrypoint: ["make init;"]
    depends_on:
      - kafka
      - mysql
      - mongodb
      - redis
      - minio
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
    networks:
      openim-server:
        ipv4_address: ${OPENIM_SERVER_NETWORK_ADDRESS:-172.28.0.8}

  openim-chat:
    image: ${IMAGE_REGISTRY:-ghcr.io/openimsdk}/openim-chat:${CHAT_BRANCH:-main}
    container_name: openim-chat
    healthcheck:
      test: ["CMD", "/openim/openim-chat/scripts/check_all.sh"]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - "${OPENIM_CHAT_API_PORT:-10008}:10008"
      - "${OPENIM_ADMIN_API_PORT:-10009}:10009"
    volumes:
      - "./openim-chat/logs:/openim/openim-chat/logs"
      - "./openim-chat/_output/logs:/openim/openim-chat/_output/logs"
      - "./openim-chat/config:/openim/openim-chat/config"
      - "./openim-chat/scripts:/openim/openim-chat/scripts"
    restart: always
    user: root:root
    depends_on:
      - mysql
      - mongodb
      - redis
      - minio
      - openim-server
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
    networks:
      openim-server:
        ipv4_address: ${OPENIM_CHAT_NETWORK_ADDRESS:-172.28.0.9}

  openim-admin:
    image: ${IMAGE_REGISTRY:-ghcr.io/openimsdk}/openim-admin-front:${ADMIN_FRONT_VERSION:-v3.4.0}
    container_name: openim-admin
    restart: always
    ports:
      - "${OPENIM_ADMIN_FRONT_PORT:-11002}:80"
    networks:
      openim-server:
        ipv4_address: ${OPENIM_ADMIN_FRONT_NETWORK_ADDRESS:-172.28.0.13}

  prometheus:
    image: prom/prometheus:${PROMETHEUS_IMAGE_VERSION:-v2.48.1}
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - "./openim-server/config/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "${PROMETHEUS_PORT:-19090}:9090"
    networks:
      openim-server:
        ipv4_address: ${PROMETHEUS_NETWORK_ADDRESS:-172.28.0.10}

  grafana:
    image: grafana/grafana:${GRAFANA_IMAGE_VERSION:-10.2.2}
    container_name: grafana
    hostname: grafana
    user: root
    restart: always
    ports:
      - "${GRAFANA_PORT:-13000}:3000"
    volumes:
      - "${DATA_DIR:-./}/components/grafana:/var/lib/grafana"
    networks:
      openim-server:
        ipv4_address: ${GRAFANA_NETWORK_ADDRESS:-172.28.0.11}

  node-exporter:
    image: bitnami/node-exporter:${NODE_EXPORTER_IMAGE_VERSION:-1.7.0}
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "${NODE_EXPORTER_PORT:-19100}:9100"
    networks:
      openim-server:
        ipv4_address: ${NODE_EXPORTER_NETWORK_ADDRESS:-172.28.0.12}